
// 這個檔案是自動生成的，請勿手動修改！
const imageGroups = [
  [
    "img/p1/1.jpg",
    "img/p1/2.jpg",
    "img/p1/3.jpg",
    "img/p1/4.jpg",
    "img/p1/5.jpg"
  ],
  [
    "img/p2/1.jpg"
  ],
  [
    "img/p3/1.jpg",
    "img/p3/2.jpg",
    "img/p3/3.jpg",
    "img/p3/4.jpg"
  ],
  [
    "img/p4/1.jpg",
    "img/p4/2.jpg",
    "img/p4/3.jpg",
    "img/p4/4.jpg",
    "img/p4/5.jpg",
    "img/p4/6.jpg",
    "img/p4/7.jpg"
  ],
  [
    "img/p5/1.jpg",
    "img/p5/2.jpg",
    "img/p5/3.jpg",
    "img/p5/4.jpg"
  ],
  [
    "img/p6/1.jpg"
  ],
  [
    "img/p7/1.jpg",
    "img/p7/10.jpg",
    "img/p7/11.jpg",
    "img/p7/12.jpg",
    "img/p7/13.jpg",
    "img/p7/14.jpg",
    "img/p7/15.jpg",
    "img/p7/16.jpg",
    "img/p7/2.jpg",
    "img/p7/3.jpg",
    "img/p7/4.jpg",
    "img/p7/5.jpg",
    "img/p7/6.jpg",
    "img/p7/7.jpg",
    "img/p7/8.jpg",
    "img/p7/9.jpg"
  ],
  [
    "img/p8/1.jpg",
    "img/p8/2.jpg",
    "img/p8/3.jpg",
    "img/p8/4.jpg"
  ],
  [
    "img/p9/1.jpg",
    "img/p9/2.jpg",
    "img/p9/3.jpg",
    "img/p9/4.jpg"
  ],
  [
    "img/p10/1.jpg",
    "img/p10/2.jpg",
    "img/p10/3.jpg"
  ],
  [
    "img/p11/1.jpg"
  ],
  [
    "img/p12/1.jpg"
  ],
  [
    "img/p13/1.jpg"
  ]
];
